spring.application.name=riskwire
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/riskwire?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
oracle.base-url=https://guidewire-devtrails-hackathon.onrender.com
spring.task.scheduling.enabled=true
