services:
  - type: web
    name: riskwire-rag-chatbot
    env: python
    plan: free
    rootDir: RAG
    pythonVersion: 3.11.8
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        scope: build
